name: mar
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.8.5
  - pip=20.3
  - pytorch-cuda=11.8
  - pytorch=2.2.2
  - torchvision=0.17.2
  - numpy=1.22
  - pip:
    - opencv-python==4.1.2.30
    - timm==0.9.12
    - tensorboard==2.10.0
    - scipy==1.9.1
    - gdown==5.2.0
    - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity
